#!/bin/sh

if which xmessage >> /dev/null 2>&1; then
	xmessage -buttons Reiniciar,Desligar,Terminal "$@" "";

	case "$?" in
		101)
			/usr/bin/systemctl reboot
			;;
		102)
			/usr/bin/systemctl poweroff
			;;
		103)
			/usr/bin/systemctl stop xdm
			;;
	esac
fi

