#!/bin/bash
# Lara Maia <lara@craft.net.br> © 2012~2013
# Modded for Gvim by BlackICE <nice, cool, cute, pretty, developer, friend, and boyfriend> <blackice@craft.net.br>
# Versão: 1.1
# --------------------

function user_not_found() {
    echo -e '\nConfiguration file not found.'
    echo -e 'It is need for access files with root permissions.\n'
    read -s -p "Write your password: " pass
    echo -e "user=$USER\npass=$pass" > ${HOME}/.config/$(basename $0).user
}

# Fix Paths with spaces
IFS=$(echo -en "\n\b")

# Config
source ${HOME}/.config/$(basename $0).user >/dev/null 2>&1 || user_not_found

if [ `id -u` == 0 ]; then
    (gvim $@) &
    exit 0
fi

function root_open() {
# $1 = pass | $2 = file
(echo $1 | sudo -S gvim $2)&>/dev/null
if [ $? != 0 ]; then
    echo -e "\nIncorrect password!\n"
    echo -e "Run again to fix this.\n"
    rm -f ${HOME}/.config/$(basename $0).user
    exit 1
fi
}

for file in ${@}; do
    if [ "${file:0:1}" == "/" ]; then

        test_file=${file%/*}
        test "$test_file" == "" && test_file="/"

        if [ "$(ls -l -d $test_file | awk '{print $3}')" == "root" ]; then
            (root_open $pass "$file") &
        else
            (gvim "$file") &
        fi
    else
        if [ "$(ls -l -d `pwd`|awk '{print $3}')" == "root" ]; then
            (root_open $pass "$file") &
        else
            (gvim "$file") &
        fi
    fi
    sleep .3
done

exit 0

